include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    # strict-casts: true
    # strict-inference: true
    # strict-raw-types: true
  errors:
    doc_directive_unknown: ignore
    non_constant_identifier_names: info
    invalid_annotation_target: ignore
    avoid_print: warning
    unsafe_html: error
    require_trailing_commas: info
    use_decorated_box: warning
    use_colored_box: warning
  exclude:
    [
      tools/*
      test/*,
      build/**,
      "**/*.freezed.dart",
      "**/*.g.dart",
      "**/*.gr.dart",
      "**/*.gen.dart",
    ]

linter:
  rules:
    - use_super_parameters
    - avoid_print
    - avoid_types_as_parameter_names
    - avoid_empty_else
    - avoid_relative_lib_imports
    - collection_methods_unrelated_type
    - control_flow_in_finally
    - empty_statements
    - prefer_void_to_null
    - use_key_in_widget_constructors
    - annotate_overrides
    - use_build_context_synchronously
    - use_string_buffers
    - use_setters_to_change_properties
    - use_rethrow_when_possible
    - use_named_constants
    - use_is_even_rather_than_modulo
    - use_if_null_to_convert_nulls_to_bools
    - use_function_type_syntax_for_parameters
    - use_full_hex_values_for_flutter_colors
    - use_decorated_box
    - use_colored_box
    - unrelated_type_equality_checks
    - unnecessary_this
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - unnecessary_new
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_null_in_if_null_operators
    - unnecessary_null_aware_assignments
    - unnecessary_getters_setters
    - unnecessary_statements
    - unnecessary_overrides
    - unnecessary_const
    - sort_child_properties_last
    - prefer_typing_uninitialized_variables
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - cancel_subscriptions
    - unnecessary_brace_in_string_interps
    - unnecessary_await_in_return
    - unawaited_futures
    - type_init_formals
    - flutter_style_todos
    - constant_identifier_names
    - omit_local_variable_types
    - one_member_abstracts
    - prefer_generic_function_type_aliases
    - prefer_collection_literals
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - prefer_expression_function_bodies
    - require_trailing_commas
    - directives_ordering
    - avoid_redundant_argument_values
    - unnecessary_parenthesis
    - prefer_final_locals
    - join_return_with_assignment
    - prefer_if_elements_to_conditional_expressions
