include: package:flutter_lints/flutter.yaml

formatter: 
  page_width: 120

linter:
  rules:
    avoid_print: true 
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_const_declarations: true