arb-dir: lib/src/common/localization
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: desiredFileName.txt
use-deferred-loading: true
preferred-supported-locales:
  - ru
  - en